# Start from the latest golang base image
FROM golang:latest

# Add Maintainer Info
LABEL maintainer="Steven"

# Set the Current Working Directory inside the container
WORKDIR /app

# Set GOPROXY to use an alternative package proxy
ENV GOPROXY=https://proxy.golang.org

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the Go application using go run .
CMD ["go", "run", "."]
